name: p_i_hub
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  carousel_slider: ^4.0.0
  cloud_firestore: ^2.5.3
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  flutter:
    sdk: flutter
  flutter_snake_navigationbar: ^0.5.0
  font_awesome_flutter: ^9.1.0
  flutter_form_builder: ^6.1.0+1
  get: 4.3.8
  google_fonts: ^2.1.0
  google_sign_in: ^5.1.0
  photo_view: ^0.12.0
  stacked_card_carousel: ^0.0.3-nullsafety.1
  url_launcher: ^6.0.10
  velocity_x: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
#   flutter_native_splash: ^1.2.4

# flutter_native_splash:
#   color: "#282934"
#   image: assets/icon.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  assets:
    - assets/icon.png
  uses-material-design: true
